version: 2
jobs:
  build:
    machine: true
    environment:
      IMAGE_NAME: ci-build
    steps:
      - checkout
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$CIRCLE_TAG .
      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$CIRCLE_TAG && sleep 10

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /\d(\.\d+)*/
